config/routes.rb
Rails.application.routes.draw do
  root 'fields#index'
  resources :fields
  post 'save_shape' => 'fields#save_shape'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/field.rb
class Field < ActiveRecord::Base
  default_scope { order(created_at: :desc) }

  class << self

    def to_map_coords(shape)
      RGeo::GeoJSON.encode(shape).to_json
    end

    def to_multipolygon(polygon)
      sql = "SELECT ST_AsText(ST_Multi(ST_GeomFromText('#{polygon}')));"
      pg_result(sql)
    end

    def area(shape)
      sql = "SELECT ST_Perimeter(ST_GeomFromText('#{shape}'));"
      pg_result(sql)
    end

    private

    def pg_result(sql)
      result = ActiveRecord::Base.connection.execute(sql)
      result.getvalue(0, 0)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: %i[show edit update destroy save_shape]

  def index
    @fields = Field.all
  end

  def show; end

  def new
    @field = Field.new
  end

  def edit; end

  def create
    params['field']['shape'] = decoded_shape(params['field']['shape'])
    @field = Field.new(field_params)
    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      shape =  params['field'].except('shape') if params['field']['shape'].include?('MULTIPOLYGON')
      params['field']['shape'] = decoded_shape(params['field']['shape']) unless shape
      if @field.update(field_params)
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @field.destroy
    respond_to do |format|
      format.html { redirect_to fields_url, notice: 'Field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def decoded_shape(params)
    coords = RGeo::GeoJSON.decode(params, json_parser: :json)
    Field.to_multipolygon(coords.geometry.as_text)
  end

  private

  def set_field
    @field = Field.find(params[:id])
  end

  def field_params
    params.require(:field).permit(:name, :shape)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fields/_form.slim
= form_for @field do |f|
  .form-group
    label for="name"  Name:
    = f.text_field :name,class:'form-control'
    = f.hidden_field :shape, id:'hidden-shape', value: @field.try(:shape)
  = f.submit 'Save', class: 'btn btn-default'

app/views/fields/edit.slim
h1 Editing Field

= link_to 'Show', @field, class: 'btn btn-success'
= link_to 'Back', fields_path, class: 'btn btn-default'

= render 'form'

#map data-field-id=@field.id data-shape=Field.to_map_coords(@field.shape)
javascript:
    init(true);

app/views/fields/index.slim
.row
  .col-md-8
    h2 Map of shapes
    table.table
      thead
        tr
          th Name
          th Area
          th Actions
      tbody
      - @fields.each do |field|
        tr
          td
            = link_to field.name, field
          td
            = Field.area(field.shape) if field.shape
          td
            = link_to 'Edit', edit_field_path(field), class: 'btn btn-warning'
            = link_to 'Destroy', field, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
  .col-md-4
    #map

#fields data-fields=@fields.map{ |field| Field.to_map_coords(field.shape) }
javascript:
    var mymap = L.map('map').setView([50.4546600, 30.5238000], 3);
    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        maxZoom: 18,
        attribution: 'test'

    }).addTo(mymap);
    var fields = $('#fields').data('fields');
    $.each(fields, function (index, value) {
        L.geoJSON(JSON.parse(value)).addTo(mymap);
    });

app/views/fields/new.slim
= render 'form'

= link_to 'Back', fields_path,class:'btn btn-default'

#map
javascript:
    init(true);

app/views/fields/show.slim
h2 Map of shapes
table.table
  thead
    tr
      th Name
      th Shape
      th Actions
  tbody
    tr
      td
        = @field.name
      td
        = Field.to_map_coords(@field.shape)
      td
        = link_to 'Edit', edit_field_path(@field), class: 'btn btn-warning'
        = link_to 'Back', fields_path, class: 'btn btn-default'



#map data-shape=Field.to_map_coords(@field.shape)
  javascript:
      init(false);

app/views/layouts/application.slim
html
  head
    title TestApp
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

.container
  nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        a.navbar-brand =link_to 'Root', root_path, class:'btn btn-default'
        a.navbar-brand =link_to 'New', new_field_path, class:'btn btn-default'
  #notice
    = notice
  = yield